interface _TMDBResponseByUrl {
  [key: string]: {
    status: number;
    body: any;
  };
}

export const tmdbResponseByUrl = {
  http_api_themoviedb_org_3_search_movie_query_shrek_2: {
    status: 200,
    body: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/iaNoLnnpQb5SNxGc4bkQmdCvEdG.jpg',
          genre_ids: [16, 10751, 35, 14, 12],
          id: 809,
          original_language: 'en',
          original_title: 'Shrek 2',
          overview:
            "Shrek, Fiona, and Donkey set off to Far, Far Away to meet Fiona's mother and father, the Queen and King. But not everyone is happily ever after. Shrek and the King find it difficult to get along, and there's tension in the marriage. The Fairy Godmother discovers that Fiona has married Shrek instead of her son Prince Charming and plots to destroy their marriage.",
          popularity: 123.22,
          poster_path: '/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg',
          release_date: '2004-05-19',
          title: 'Shrek 2',
          video: false,
          vote_average: 7.274,
          vote_count: 11989,
        },
        {
          adult: false,
          backdrop_path: '/9QXx4tS65s3oUBoQ27bMIwmBD9x.jpg',
          genre_ids: [16, 35, 10751],
          id: 48466,
          original_language: 'en',
          original_title: 'Scared Shrekless',
          overview:
            "Shrek challenges Donkey, Puss in Boots and his other fairy tale character friends to spend the night in Lord Farquaad's haunted castle, telling scary stories to see who can resist becoming scared and stay the longest.",
          popularity: 25.875,
          poster_path: '/aAQQJhX8NqKZ7ZNDUPQQKi1wK8h.jpg',
          release_date: '2010-10-28',
          title: 'Scared Shrekless',
          video: false,
          vote_average: 6.628,
          vote_count: 437,
        },
        {
          adult: false,
          backdrop_path: '/2VrSMfNDNGpzIowiiIpS3JUXLf4.jpg',
          genre_ids: [16, 35],
          id: 82530,
          original_language: 'en',
          original_title: 'The Pig Who Cried Werewolf',
          overview:
            "Of the famous Three Little Pigs, Heimlich is the one porker who finds a conspiracy around every corner. When The Big Bad Wolf moves in next door, Heimlich tries to warn his piggy pals Horst and Dieter that this may not bring a fairy-tale ending. Tired of hearing him 'cry wolf,' they ignore Heimlich's warnings until it's almost too late for them to live happily ever after. The chase is on!",
          popularity: 11.122,
          poster_path: '/vL0j4H2VKfX5CERqA5NtHpvp0Lq.jpg',
          release_date: '2011-10-04',
          title: 'The Pig Who Cried Werewolf',
          video: false,
          vote_average: 6.167,
          vote_count: 60,
        },
      ],
      total_pages: 1,
      total_results: 3,
    },
  },
  http_api_themoviedb_org_3_search_movie_query_amongus: {
    status: 200,
    body: {
      page: 1,
      results: [],
      total_pages: 1,
      total_results: 0,
    },
  },
  http_api_themoviedb_org_3_search_tv_query_one_piece: {
    status: 200,
    body: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
          genre_ids: [10759, 10765],
          id: 111110,
          origin_country: ['US'],
          original_language: 'en',
          original_name: 'ONE PIECE',
          overview:
            'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
          popularity: 131.865,
          poster_path: '/rVX05xRKS5JhEYQFObCi4lAnZT4.jpg',
          first_air_date: '2023-08-31',
          name: 'ONE PIECE',
          vote_average: 8.18,
          vote_count: 1073,
        },
        {
          adult: false,
          backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
          genre_ids: [10759, 35, 16],
          id: 37854,
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'ワンピース',
          overview:
            'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
          popularity: 181.415,
          poster_path: '/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
          first_air_date: '1999-10-20',
          name: 'One Piece',
          vote_average: 8.721,
          vote_count: 4513,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [],
          id: 243471,
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'ワンピース キャラクターズLog',
          overview:
            'One Piece Characters Log is a series of recap episodes for the One Piece anime, made to commemorate the release of One Piece Film: Gold. The episodes recap the stories of each of the nine Straw Hat Pirates until the Dressrosa Arc, and are narrated by Bartolomeo. Each episode is around 30 minutes. Originally airing weekly on television from June 19 to September 11, 2016, the episodes were also released on four DVDs',
          popularity: 42.677,
          poster_path: '/8hlZnRM5942aTbi4f2uIp1T6K0P.jpg',
          first_air_date: '2016-06-19',
          name: 'One Piece Characters Log',
          vote_average: 8,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: '/wrV9hbOH3pYAsNZcQ609cjnlXt5.jpg',
          genre_ids: [16, 10759, 35],
          id: 241709,
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'THE ONE PIECE',
          overview:
            'A remake of the One Piece anime for Netflix will recreate the story of the original "ONE PIECE" manga, starting from the East Blue arc.',
          popularity: 31.284,
          poster_path: '/xGcPlcZ3fx3DlEGYB7ybky3V6Rh.jpg',
          first_air_date: '',
          name: 'THE ONE PIECE',
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: '/9u6bqyTLassTHkLFmqUMy7ceAba.jpg',
          genre_ids: [16, 18, 10765],
          id: 37534,
          origin_country: ['JP'],
          original_language: 'ja',
          original_name: 'うた∽かた',
          overview:
            'Before you make a deal with a girl in a mirror, reflect seriously on the source of the offer. Ichika fails to heed this advice when she attempts to retrieve a lost charm, and suddenly finds herself with the powers of a Djinn at her command. At first things seem wondrous; but as her abilities grow, Ichika’s situation quickly goes from magical to nightmarish. Soon Ichika finds herself drawn into an ever-expanding web of deceptions, lies, and increasingly dangerous situations.',
          popularity: 47.658,
          poster_path: '/8AM1KrRrJrD1mK7uc1auQMHRmp5.jpg',
          first_air_date: '2004-10-03',
          name: 'Uta~Kata',
          vote_average: 8.2,
          vote_count: 4,
        },
        {
          adult: false,
          backdrop_path: '/pcyVB92oAuA2PQR8aoDurLETNda.jpg',
          genre_ids: [18],
          id: 99112,
          origin_country: ['KR'],
          original_language: 'ko',
          original_name: '반의 반',
          overview:
            'Moon Ha-won is an AI programmer and he is the founder of AH Company. He is a consistent person with a good heart. Meanwhile, Han Seo-woo works as a classical music recording engineer. Her life is unstable without a family or house, but she is a positive person.',
          popularity: 56.546,
          poster_path: '/u25Bd08J1kdsLXdHymXkFJsseV7.jpg',
          first_air_date: '2020-03-23',
          name: 'A Piece of Your Mind',
          vote_average: 7.5,
          vote_count: 32,
        },
      ],
      total_pages: 1,
      total_results: 6,
    },
  },
  http_api_themoviedb_org_3_search_tv_query_hell_divers: {
    status: 200,
    body: {
      page: 1,
      results: [],
      total_pages: 1,
      total_results: 0,
    },
  },
  http_api_themoviedb_org_3_tv_111110: {
    status: 200,
    body: {
      adult: false,
      backdrop_path: '/qD211Hb5XwFxrszzBBe5EUYJerh.jpg',
      created_by: [
        {
          id: 1562489,
          credit_id: '64f0824de0ca7f00ae390791',
          name: 'Matt Owens',
          original_name: 'Matt Owens',
          gender: 2,
          profile_path: null,
        },
        {
          id: 1225826,
          credit_id: '64f08253caa50800e951a4f1',
          name: 'Steven Maeda',
          original_name: 'Steven Maeda',
          gender: 2,
          profile_path: null,
        },
      ],
      episode_run_time: [],
      first_air_date: '2023-08-31',
      genres: [
        {
          id: 10759,
          name: 'Action & Adventure',
        },
        {
          id: 10765,
          name: 'Sci-Fi & Fantasy',
        },
      ],
      homepage: 'https://www.netflix.com/title/80217863',
      id: 111110,
      in_production: true,
      languages: ['en'],
      last_air_date: '2023-08-31',
      last_episode_to_air: {
        id: 4557395,
        name: 'WORST IN THE EAST',
        overview:
          'The Straw Hat crew strives to take down Arlong and the Fishmen once and for all. After a tense family reunion, Luffy inches closer to his dreams.',
        vote_average: 8.093,
        vote_count: 43,
        air_date: '2023-08-31',
        episode_number: 8,
        episode_type: 'finale',
        production_code: '',
        runtime: 51,
        season_number: 1,
        show_id: 111110,
        still_path: '/bArQFV2aEzirYlJrI592qcJYOCf.jpg',
      },
      name: 'ONE PIECE',
      next_episode_to_air: null,
      networks: [
        {
          id: 213,
          logo_path: '/wwemzKWzjKYJFfCeiB57q3r4Bcm.png',
          name: 'Netflix',
          origin_country: '',
        },
      ],
      number_of_episodes: 8,
      number_of_seasons: 2,
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'ONE PIECE',
      overview: 'With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure.',
      popularity: 131.865,
      poster_path: '/rVX05xRKS5JhEYQFObCi4lAnZT4.jpg',
      production_companies: [
        {
          id: 104720,
          logo_path: '/465nRotlMZXuB7Mlvh8o8O7BlGF.png',
          name: 'Tomorrow Studios',
          origin_country: 'US',
        },
        {
          id: 207514,
          logo_path: null,
          name: 'Kaji Productions',
          origin_country: 'US',
        },
        {
          id: 773,
          logo_path: '/qkcN6yZEyBw3cgO5DJu55LGEsf7.png',
          name: 'Film Afrika',
          origin_country: 'ZA',
        },
        {
          id: 178464,
          logo_path: '/tyHnxjQJLH6h4iDQKhN5iqebWmX.png',
          name: 'Netflix',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'ZA',
          name: 'South Africa',
        },
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      seasons: [
        {
          air_date: '2023-08-30',
          episode_count: 8,
          id: 164867,
          name: 'ONE PIECE',
          overview: '',
          poster_path: '/kzuzfuWJ0uzFkrsNuHHaWsk4G7w.jpg',
          season_number: 1,
          vote_average: 8.2,
        },
        {
          air_date: null,
          episode_count: 1,
          id: 400466,
          name: 'Season 2',
          overview: '',
          poster_path: null,
          season_number: 2,
          vote_average: 0,
        },
      ],
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Returning Series',
      tagline: 'The pirates are coming.',
      type: 'Scripted',
      vote_average: 8.18,
      vote_count: 1073,
    },
  },
  http_api_themoviedb_org_3_movie_809: {
    status: 200,
    body: {
      adult: false,
      backdrop_path: '/iaNoLnnpQb5SNxGc4bkQmdCvEdG.jpg',
      belongs_to_collection: {
        id: 2150,
        name: 'Shrek Collection',
        poster_path: '/qNHZMe92A7Pyl46qUH29hVOtbSK.jpg',
        backdrop_path: '/gMWrKQjoTIpYjhc8SxZF20EDIES.jpg',
      },
      budget: 150000000,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 10751,
          name: 'Family',
        },
        {
          id: 35,
          name: 'Comedy',
        },
        {
          id: 14,
          name: 'Fantasy',
        },
        {
          id: 12,
          name: 'Adventure',
        },
      ],
      homepage: 'http://www.shrek2.com/',
      id: 809,
      imdb_id: 'tt0298148',
      origin_country: ['US'],
      original_language: 'en',
      original_title: 'Shrek 2',
      overview:
        "Shrek, Fiona, and Donkey set off to Far, Far Away to meet Fiona's mother and father, the Queen and King. But not everyone is happily ever after. Shrek and the King find it difficult to get along, and there's tension in the marriage. The Fairy Godmother discovers that Fiona has married Shrek instead of her son Prince Charming and plots to destroy their marriage.",
      popularity: 123.22,
      poster_path: '/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg',
      production_companies: [
        {
          id: 521,
          logo_path: '/kP7t6RwGz2AvvTkvnI1uteEwHet.png',
          name: 'DreamWorks Animation',
          origin_country: 'US',
        },
        {
          id: 520,
          logo_path: '/pU7YTI9FfrICurXpl5V9TfCO0oJ.png',
          name: 'Pacific Data Images',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2004-05-19',
      revenue: 932396221,
      runtime: 92,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Once upon another time...',
      title: 'Shrek 2',
      video: false,
      vote_average: 7.274,
      vote_count: 11989,
    },
  },
  http_api_themoviedb_org_3_movie_555555555: {
    status: 404,
    body: {
      success: false,
      status_code: 34,
      status_message: 'The resource you requested could not be found.',
    },
  },
  http_api_themoviedb_org_3_tv_999999999: {
    status: 404,
    body: {
      success: false,
      status_code: 34,
      status_message: 'The resource you requested could not be found.',
    },
  },
};
