version: "4.28.0"

services:
  netix-redis:
    image: redis:7.2.4-bookworm
    container_name: cont-netix-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass pass_r1
    volumes:
      - type: bind
        source: ./data/redis
        target: /data
    restart: unless-stopped
  
  netix-mongodb:
    image: mongodb/mongodb-community-server:4.4.16-ubi8
    container_name: cont-netix-mongodb
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: ./data/mongodb
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user_m1
      - MONGO_INITDB_ROOT_PASSWORD=pass_m1
    restart: unless-stopped

volumes:
  netix-redis:
    driver: local
  netix-mongodb:
    driver: local