import { MovieDTO } from '@ntx-shared/models/movie.dto';

export const testMovieFixture: MovieDTO[] = [
  {
    id: '1',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Inception',
    summary: 'A thief who steals corporate secrets through the use of dream-sharing technology.',
    originallyReleasedAt: new Date('2010-11-07'),
    runtimeMinutes: 10140,
    posterID: 'https://fastly.picsum.photos/id/986/700/900.jpg?hmac=Z6XTg0SLdISSLjJxY7L15daSPBlIl0is-pHMS2sGDCo',
    isPublished: true,
  },
  {
    id: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Interstellar',
    summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    originallyReleasedAt: new Date('2014-11-07'),
    runtimeMinutes: 10140,
    posterID: 'https://fastly.picsum.photos/id/410/700/900.jpg?hmac=7bkyN8_CkLEpktiIL8SQj9YV2-Bgv-u3AIkBsMhDQSM',
    isPublished: true,
  },
  {
    id: '3',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'The Matrix',
    summary: 'A computer hacker learns from mysterious rebels about the true nature of his reality.',
    originallyReleasedAt: new Date('1999-11-07'),
    runtimeMinutes: 9140,
    posterID: 'https://fastly.picsum.photos/id/729/700/900.jpg?hmac=dkrDGdKLxPWTVcfUtk9oBeviL3snwldFOMo9QG5f1EU',
    isPublished: true,
  },
  {
    id: '4',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Pulp Fiction',
    summary: 'The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.',
    originallyReleasedAt: new Date('1994-11-07'),
    runtimeMinutes: 10000,
    posterID: 'https://fastly.picsum.photos/id/172/700/900.jpg?hmac=j92ReRNGl367wrJYLhaSHNa61DFyORGCaSqWWSUooqw',
    isPublished: true,
  },
  {
    id: '5',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Blade Runner 2049',
    summary: "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.",
    originallyReleasedAt: new Date('2017-11-07'),
    runtimeMinutes: 9890,
    posterID: 'https://fastly.picsum.photos/id/344/700/900.jpg?hmac=XwfWpOhCSDOwm7KOpSCD8s7dZCJMTInlxl2k48xQNow',
    isPublished: true,
  },
  {
    id: '6',
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'London will fall with the human race',
    summary: 'A post-apocalyptic story where humanity struggles to survive as London falls.',
    originallyReleasedAt: new Date('2017-11-07'),
    runtimeMinutes: 9890,
    posterID: 'https://fastly.picsum.photos/id/690/700/800.jpg?hmac=11qu0nO1sNp6VYfM9qhziv8t9It_5KC2zFe5rwMBY4I',
    isPublished: true,
  },
];
