{
 "title": "API monitoring",
 "time": { "from": "2024-11-27T13:00:35.065Z", "to": "2024-11-27T13:29:38.650Z" },
 "panels": [
  {
   "title": "Requests details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"2.*\"}[1m])) by (route, method, code)    ",
     "legendFormat": "2xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"4.*\"}[1m])) by (route, method, code)",
     "legendFormat": "4xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"5.*\"}[1m])) by (route, method, code) ",
     "legendFormat": "5xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"3.*\"}[1m])) by (route, method, code) ",
     "legendFormat": "3xx {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Average Routes Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_ms_sum[$__range]) / rate(http_request_duration_ms_count[$__range])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "90th 95th and 99th respones time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "90th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "95th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "99th {{method}} {{route}}"
    }
   ]
  }
 ]
}