global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'netix-ap monitoring'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['host.docker.internal:3055']
      # - targets: ['172.25.32.1:3055']
