export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const MONGODB_URI = 'MONGODB_URI';
export const USE_MEMORY_MONGO = 'USE_MEMORY_MONGO';
export const IN_MEMORY_MONGO_PORT = 'IN_MEMORY_MONGO_PORT';
