name: Backend CI

on:
  push:
    branches:
      - 'develop'
    paths: 
      - 'ntx-backend-nestjs/**'
  pull_request:
    paths:
      - 'ntx-backend-nestjs/**'

jobs:
  backend:
    name: NestJS BE APP Build and Test
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    concurrency:
      group: backend-ci-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ./ntx-backend-nestjs/node_modules
          key: ntx-backend-nestjs-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/ntx-backend-nestjs/package-lock.json') }}
          restore-keys: |
            ntx-backend-nestjs-${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/ntx-backend-nestjs/package-lock.json'
        
      - name: Install dependencies (if node_modules cache not found)
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        working-directory: ntx-backend-nestjs
        run: npm ci

      - name: Run lint
        working-directory: ntx-backend-nestjs
        run: npm run lint

      - name: Build
        working-directory: ntx-backend-nestjs
        run: npm run build

      - name: Run tests
        working-directory: ntx-backend-nestjs
        run: npm run test-ci
